module.exports = {
  extends: ['@commitlint/config-conventional'],
  parserPreset: {
    parserOpts: {
      headerPattern: /^(.*?)([A-Za-z]+)(?:\((.*)\))?:\s*(.*)$/,
      headerCorrespondence: ['emoji', 'type', 'scope', 'subject'],
    },
  },
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'build',
        'chore',
        'ci',
        'docs',
        'feat',
        'fix',
        'perf',
        'refactor',
        'revert',
        'style',
        'test',
        'Build',
        'Chore',
        'Ci',
        'Docs',
        'Feat',
        'Fix',
        'Perf',
        'Refactor',
        'Revert',
        'Style',
        'Test',
      ],
    ],
    'type-empty': [2, 'never'],
    'subject-empty': [2, 'never'],
    'type-case': [0],
    'subject-case': [0],
    'subject-full-stop': [0],
    'header-max-length': [0],
    'scope-case': [0],
    'scope-empty': [0],
    'body-max-line-length': [0],
    'body-leading-blank': [0],
    'footer-leading-blank': [0],
    'footer-max-line-length': [0],
  },
};
